CREATE TABLE PRODUCT (
  product_id INTEGER PRIMARY KEY,
  quantity DECIMAL,
  name_bg VARCHAR(250),
  name_eng VARCHAR(250),
  room INTEGER,
  "batch" INTEGER,
  act_ingr INTEGER
);
CREATE TABLE MEDIC (
  "has_prescription" NUMBER(1,0),
  "group" INTEGER,
  "product" INTEGER
);
CREATE TABLE SUPPLEMENT (
  "quantity" decimal,
  "num" int,
  "product" int
);

CREATE TABLE ROOM (
  "room_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE BATCHES (
  "batch_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "price" decimal,
  "shelf_life" timestamp
);
CREATE TABLE ACTIVE_INGR (
  "ingr_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_bg" varchar(250),
  "name_eng" varchar(250)
);

CREATE TABLE DRUG_GROUP (
  "group_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_bg" varchar(250),
  "name_eng" varchar(250)
);

CREATE TABLE E_NUM (
  "e_num_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name_bg" varchar(250),
  "name_eng" varchar(250),
  "group" varchar(250)
);

CREATE TABLE ORDERS (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE ORDER_IN (
  "date_in" timestamp,
  "order" int,
  "distributor" int
);

CREATE TABLE ORDER_OUT (
  "date_out" timestamp,
  "order" int,
  "pharmacy" int
);

CREATE TABLE PHARMACY (
  "ph_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adress" varchar(250)
);

CREATE TABLE DISTRIBUTOR (
  "dis_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(250)
);

CREATE TABLE ORDER_PRODUCT (
  "order" int,
  "product" int,
  "quantity" int,
  "price_piece" decimal
);

ALTER TABLE PRODUCT ADD FOREIGN KEY ("batch") REFERENCES BATCHES("batch_id");

CREATE TABLE ACT_INGR_PRODUCT (
  "act_ingrs_ingr_id" int,
  "products_act_ingr" int,
  PRIMARY KEY ("act_ingrs_ingr_id", "products_act_ingr")
);

ALTER TABLE "ACT_INGR_PRODUCT" ADD FOREIGN KEY ("act_ingrs_ingr_id") REFERENCES ACTIVE_INGR ("ingr_id");
/* TABLE "ACT_INGR_PRODUCT" ADD FOREIGN KEY ("products_act_ingr") REFERENCES PRODUCT(ACT_INGR);*/
 ALTER TABLE "ACT_INGR_PRODUCT" ADD FOREIGN KEY ("products_id") REFERENCES PRODUCT(PRODUCT_ID);


ALTER TABLE MEDIC ADD FOREIGN KEY ("group") REFERENCES DRUG_GROUP ("group_id");

ALTER TABLE MEDIC ADD FOREIGN KEY ("product") REFERENCES PRODUCT (PRODUCT_ID);

ALTER TABLE SUPPLEMENT ADD FOREIGN KEY ("num") REFERENCES E_NUM("e_num_id");

ALTER TABLE SUPPLEMENT ADD FOREIGN KEY ("product") REFERENCES PRODUCT (PRODUCT_ID);

ALTER TABLE ORDER_IN ADD FOREIGN KEY ("order") REFERENCES ORDERS ("order_id");

ALTER TABLE ORDER_IN ADD FOREIGN KEY ("distributor") REFERENCES DISTRIBUTOR ("dis_id");

ALTER TABLE ORDER_OUT ADD FOREIGN KEY ("order") REFERENCES ORDERS ("order_id");

ALTER TABLE ORDER_OUT ADD FOREIGN KEY ("pharmacy") REFERENCES PHARMACY ("ph_id");

ALTER TABLE ORDER_PRODUCT ADD FOREIGN KEY ("order") REFERENCES ORDERS ("order_id");

ALTER TABLE ORDER_PRODUCT ADD FOREIGN KEY ("product") REFERENCES PRODUCT (product_id);

ALTER TABLE PRODUCT ADD FOREIGN KEY (room) REFERENCES ROOM("room_id");


INSERT ALL
INTO ROOM VALUES ('001')
INTO ROOM VALUES ('002')
INTO ROOM VALUES ('003')
INTO ROOM VALUES ('004')
SELECT 1 FROM DUAL;

INSERT ALL
INTO PHARMACY VALUES ('1', 'Adress 1')
INTO PHARMACY VALUES ('2', 'Adress 2')
SELECT 1 FROM DUAL;

INSERT ALL
INTO DISTRIBUTOR VALUES ('1', 'Distributor 1')
INTO DISTRIBUTOR VALUES ('2', 'Distributor 2')
SELECT 1 FROM DUAL;

INSERT ALL
INTO DRUG_GROUP VALUES ('1', 'lekarstvena grupa 1', 'Drug Group 1 ')
INTO DRUG_GROUP VALUES ('2', 'lekarstvena grupa 2', 'Drug Group 2 ')
INTO DRUG_GROUP VALUES ('3', 'lekarstvena grupa 3', 'Drug Group 3 ')
SELECT 1 FROM DUAL;

INSERT ALL
INTO E_NUM VALUES ('100', 'ocvetiteli v julto', 'yellow food colour', 'food colours')
INTO E_NUM VALUES ('110', 'ocvetiteli v oranjevo', 'orange food colour', 'food colours')
INTO E_NUM VALUES ('220', 'silfidi', 'sulphids', 'conservants')
INTO E_NUM VALUES ('240', 'nitrati', 'nitrats', 'conservants')
SELECT 1 FROM DUAL;

INSERT ALL
INTO BATCHES VALUES (1, '10.5',CURRENT_TIMESTAMP)
INTO BATCHES VALUES (2, '5.2', CURRENT_TIMESTAMP)
SELECT 1 FROM DUAL;
INSERT INTO BATCHES VALUES (3, '15.2', timestamp '2017-10-12 21:22:23');
SELECT * FROM BATCHES;

INSERT ALL
INTO ACTIVE_INGR VALUES (1,'aktivna sustavka 1', 'active ingredient 1')
INTO ACTIVE_INGR VALUES (2,'aktivna sustavka 2', 'active ingredient 2')
INTO ACTIVE_INGR VALUES (3,'aktivna sustavka 3', 'active ingredient 3')
SELECT 1 FROM DUAL;


/*??????????? ? ?????????? ??????? ?? ?????????????? ?? ???????, ???? ?? ??????? ?????????? ??? ?????????? ??????? ?? ???????? ???????? ? ? ????? ???????*/
INSERT ALL
INTO PRODUCT VALUES (5, 100, 'medikament 1', 'medicament 1', 1, 1, 1)
INTO PRODUCT VALUES (6, 100, 'medikament 2', 'medicament 2', 1, 2, 1)
INTO PRODUCT VALUES (7, 90, 'hranitelna dobavka 1', 'supplement 1', 2, 2, 2)
INTO PRODUCT VALUES (8, 35, 'hranitelna dobavka 2', 'supplement 2', 2, 2, 2)
SELECT 1 FROM DUAL;

SELECT * FROM PRODUCT; 
/*ALTER TABLE MEDIC ADD medic_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
ALTER TABLE MEDIC DROP COLUMN medic_id;
*/
SELECT * FROM E_NUM;

INSERT ALL
INTO MEDIC VALUES (0, 1, 1)
INTO MEDIC VALUES (1, 2, 2)
SELECT 1 FROM DUAL;

INSERT ALL
INTO SUPPLEMENT VALUES (100, 100, 3)
INTO SUPPLEMENT VALUES (100, 220, 4)
SELECT 1 FROM DUAL;

SELECT * FROM ROOM;
SELECT * FROM PHARMACY;
SELECT * FROM E_NUM;
SELECT * FROM PRODUCT; 
SELECT * FROM MEDIC;
SELECT * FROM SUPPLEMENT;

INSERT ALL
INTO ACT_INGR_PRODUCT VALUES (1,1)
INTO ACT_INGR_PRODUCT VALUES (1,2)
INTO ACT_INGR_PRODUCT VALUES (2,1)
SELECT 1 FROM DUAL;
SELECT * FROM ACT_INGR_PRODUCT;

/*??????? - ???????? ?? ????? ?? ??????????? ? ?? ????? ?? ??????*/
INSERT ALL
INTO ORDERS VALUES (1)
INTO ORDERS VALUES (2)
INTO ORDERS VALUES (3)
INTO ORDERS VALUES (4)
SELECT 1 FROM DUAL;

INSERT ALL
INTO ORDER_IN VALUES (CURRENT_TIMESTAMP,1,1)
INTO ORDER_IN VALUES (CURRENT_TIMESTAMP,2,1)
INTO ORDER_OUT VALUES (CURRENT_TIMESTAMP,3,1)
INTO ORDER_OUT VALUES (CURRENT_TIMESTAMP,4,1)
SELECT 1 FROM DUAL;
/*DELETE FROM ORDER_OUT;*/ 

SELECT * FROM ROOM;
SELECT * FROM ORDER_OUT;

/*DELETE FROM ORDER_PRODUCT;*/
INSERT ALL
INTO ORDER_PRODUCT VALUES(1,1,10,10)
INTO ORDER_PRODUCT VALUES(1,2,5,50)
INTO ORDER_PRODUCT VALUES(2,1,10,10)
INTO ORDER_PRODUCT VALUES(3,1,10,10)
INTO ORDER_PRODUCT VALUES(3,3,10,10)
INTO ORDER_PRODUCT VALUES(4,3,10,10)

SELECT 1 FROM DUAL;
/*XML ?????*/
ALTER TABLE DISTRIBUTOR ADD address XMLTYPE;
INSERT INTO DISTRIBUTOR VALUES (
 '3','Distributor 3',
 XMLType('<Address> 
            <Street>Street1</Street>
            <Num>12</Num>
            <City>City1</City>
            <Postcode>2000</Postcode>
          </Address>'));
SELECT * FROM DISTRIBUTOR;

INSERT INTO ROOM VALUES (5); SELECT * FROM ROOM;


  SELECT op."order", op."product", op."quantity", op."price_piece", p.NAME_BG, p.NAME_ENG, p."batch", p.ACT_INGR, ai."name_eng", ai."name_bg"
  FROM ORDER_PRODUCT op 
  LEFT JOIN PRODUCT p ON  op."product" =  p.product_id 
  LEFT JOIN ACTIVE_INGR ai  ON ai."ingr_id" = p.ACT_INGR
  WHERE op."order" = 1;
  
  SELECT * FROM ROOM;
  DELETE FROM ROOM WHERE "room_id" = 21;
  
  SELECT p.product_id, p.quantity, p.name_bg, p.name_eng, p.room, p."batch", p.act_ingr, m."has_prescription", m."group", s."quantity", s."num"
  FROM PRODUCT p
   JOIN MEDIC m
  ON p.product_id = m."product"
   JOIN SUPPLEMENT s
  ON p.product_id = s."product";
  SELECT * FROM ORDER_IN;
  
